name: Android Debug Build
on: workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: 18

      - name: Setup Android SDK
        uses: android-actions/setup-android@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.3.7

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null
          haxelib install lime 8.1.2
          haxelib install openfl 9.3.3
          haxelib --never install flixel 5.6.1
          haxelib run lime setup flixel
          haxelib install flixel-addons 3.2.2
          haxelib install flixel-tools 1.5.1
          haxelib install hscript-iris 1.1.3
          haxelib install tjson 1.4.0
          haxelib install hxdiscord_rpc 1.2.4
          haxelib install hxvlc 2.0.1 --skip-dependencies
          haxelib git extension-androidtools https://github.com/Default-name123/oldtools
          haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate 768740a56b26aa0c072720e0d1236b94afe68e3e
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit 1906c4a96f6bb6df66562b3f24c62f4c5bba14a7
          haxelib git funkin.vis https://github.com/FunkinCrew/funkVis 22b1ce089dd924f15cdc4632397ef3504d464e90
          haxelib git grig.audio https://gitlab.com/haxe-grig/grig.audio.git cbf91e2180fd2e374924fe74844086aab7891666
          haxelib install hxcpp-debug-server

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib set lime 8.1.2
          haxelib set openfl 9.3.3
          haxelib set flixel 5.6.1
          haxelib set flixel-addons 3.2.2
          haxelib set hxcpp 4.2.1
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Building (Debug)
        run: haxelib run lime build android -debug

      - name: Upload APK
        uses: actions/upload-artifact@main
        with:
          name: Android-Debug-APK
          # O caminho abaixo busca qualquer APK gerado na pasta de output
          path: export/release/android/bin/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
